---
title: 'Assignment: Due Wednesday, 11:59pm'
author: "Your Name Here"
date: "September 21, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
```

## 1. MITM for 3DES

Consider the meet-in-the-middle attack on Triple DES described in the notes.

a. Assuming that $m$ is a single block (64 bits), calculate the number of bytes that need to be stored in Step 3 of this attack. (1 byte = 8 bits)
$$
22 \times {2^{56}}^{56}
$$

$$
The 22 is from storing the ciphertext and each key. The ciphertext being 8 bytes and each key being 7 bytes.
The {2^{56}}^{56} comes from each key pair having another key pair.
$$

b. Calculate the number of times the DES function needs to be executed ($D$ or $D^{-1}$).
$$
{2^{56}}^{56} \times 2^{56}
$$
We need another 2 to the 56 keys to decrypt what we found.

c. If your computer can crack Double DES in one day, approximately how long will it take to crack Triple DES?
$$
\frac{2^{56} + {2^{56}}^{56}}{2^{57}}
$$

Since the time to crack 2DES is 2^{57} (The number is from the numbers of keys to check) and we know that the time to decrypt 3DES from 1b is {2^{56}}^{56} \times 2^{56} the time to crack 3DES would be the division of the two numbers. 

Explain your reasoning in complete sentences. 

## 2. Finite Fields

Consider the field $F = \mathbb{Z}_2/(x^3+x+1)$.

a. How many elements does $F$ have? List them (as polynomials).

$$
8\\
0, 1, x, x+1, x^2, x^2+1, x^2+x, x^2+x+1
$$

b. For each nonzero element you found in part (a), give its multiplicative inverse.
$$
1^{-1} = 1\\
x^{-1} = x^2+1\\
{x+1}^{-1} = x^2+x\\
{x^2}^{-1} = x^2+x+1\\
{x^2+1}^{-1} = x\\
{x^2+x}^{-1} = x+1\\
{x^2+x+1}^{-1} = x^2\\
$$
